# Generated by Django 4.0.4 on 2022-04-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('url', models.URLField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('is_question', models.BooleanField(default=False)),
                ('is_thread', models.BooleanField(default=False)),
                ('is_fetched', models.BooleanField(default=False)),
                ('threads', models.ManyToManyField(null=True, related_name='replies', to='main.thread')),
            ],
        ),
    ]
