# Generated by Django 4.0.4 on 2022-04-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='threads',
            field=models.ManyToManyField(related_name='replies', to='main.thread'),
        ),
    ]
