# Generated by Django 4.0.4 on 2022-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tweet_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_others',
            field=models.BooleanField(default=False),
        ),
    ]
